# Site settings
title: JL Blog
SEOTitle: 瑾熙的博客 | JL Blog
header-img: img/1556966015452.jpg
email: 1543192060.qq.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 瑾熙的博客, caosw, 曹胜旺, iOS, Apple, iPhone"
url: "https://caosw199509.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/caosw199509/caosw199509.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Live beautifully, dream passionately, love completely."
sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     5691119853
zhihu_username:     cao-sheng-wang-20
github_username:    caosw199509
#facebook_username:  caosw
jianshu_username:   50876fe163a4
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: caosw199509

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 19fc9f4e99c6d1507538                            #生成的clientID
  clientSecret: 4b7f3b81621ea7fe73656bf56d0aa38febb58274    #生成的clientSecret
  repo: caosw199509.github.io    #仓库名称
  owner: caosw199509    #github用户名
  admin: caosw199509
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 805f9cb837854873798e7f734beda365

# Google Analytics
ga_track_id: 'UA-145656306-1'            # Format: UA-xxxxxx-xx
ga_domain: caosw.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Baidu",
        href: "http://www.baidu.com"
    },{
        title: "简书",
        href: "https://www.jianshu.com"
    },{
        title: "Google",
        href: "https://www.google.com"
    }
]
